# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.9"

gem "serverspec", "~> 2.41"
gem "rspec_junit_formatter", "~> 0.4.1"
gem "octopus-serverspec-extensions", "~> 0.17.2"
